export type ReactionType = 'like' | 'love' | 'haha';

export interface NewsComment {
    id: number;
    user: string;
    comment: string;
    timestamp: string;
    reactions: { [K in ReactionType]?: number };
    userReaction?: ReactionType;
    replies: NewsComment[];
}

export interface NewsArticle {
    article_id: string;
    title: string;
    category: string[];
    author: string;
    date: string;
    image_url: string;
    snippet: string;
    link?: string;
    keywords?: string[];
    description?: string;
    sourceName?: string;
    creator?: string[];
    pubDate?: string;
    content?: string;
    pubDateTZ?: string;
    video_url?: string | null;
    source_id?: string;
    source_name?: string;
    source_priority?: number;
    source_url?: string;
    source_icon?: string;
    language?: string;
    country?: string[];
    sentiment?: string;
    sentiment_stats?: string;
    ai_tag?: string;
    ai_region?: string;
    ai_org?: string;
    ai_summary?: string;
    ai_content?: string;
    duplicate?: boolean;
    comments?: NewsComment[];
}

export const mockNews: NewsArticle[] = [
    {
        article_id: "c1c7da70db430188a5c014f342b47459",
        title: "৩ দাবিতে কমপ্লিট শাটডাউনে দেশের সব প্রকৌশল বিশ্ববিদ্যালয়",
        link: "https://www.banglatribune.com/others/912949/%E0%A7%A9-%E0%A6%A6%E0%A6%BE%E0%A6%AC%E0%A6%BF%E0%A6%A4%E0%A7%87-%E0%A6%95%E0%A6%AE%E0%A7%8D%E0%A6%AA%E0%A7%8D%E0%A6%B2%E0%A6%BF%E0%A6%9F-%E0%A6%B6%E0%A6%BE%E0%A6%9F%E0%A6%A1%E0%A6%BE%E0%A6%89%E0%A6%A8%E0%A7%87-%E0%A6%A6%E0%A7%87%E0%A6%B6%E0%A7%87%E0%A6%B0-%E0%A6%B8%E0%A6%AC-%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%95%E0%A7%8C%E0%A6%B6%E0%A6%B2",
        keywords: ["চুয়েট", "রুয়েট", "বুয়েট"],
        creator: ["ঢাবি প্রতিনিধি"],
        description: "তিন দাবিতে দেশের সব প্রকৌশল বিশ্ববিদ্যালয়ে 'কমপ্লিট শাটডাউন' কর্মসূচি পালন করছেন শিক্ষার্থীরা। বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয়ে (বুয়েট) বন্ধ রয়েছে সব ধরনের পরীক্ষাও।বুধবার (২৭ আগস্ট) শাহবাগ থেকে এ কর্মসূচি ঘোষণার পর বৃহস্পতিবার (২৮ আগস্ট) সকাল থেকে ক্লাস পরীক্ষা বন্ধ রয়েছে প্রকৌশল বিশ্ববিদ্যালয়গুলোতে। এর আগে, বুধবার রাতে এক সংবাদ সম্মেলনে আন্দোলনরত শিক্ষার্থীদের প্ল্যাটফর্ম...বিস্তারিত",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:42:09",
        pubDateTZ: "UTC",
        image_url: "https://cdn.banglatribune.net/contents/cache/images/800x450x1/uploads/media/2025/08/28/1-89940b39953854abe291947d49916dfa.jpg?jadewits_media_id=990909",
        video_url: null,
        source_id: "banglatribune",
        source_name: "Bangla Tribuna",
        source_priority: 685343,
        source_url: "https://www.banglatribune.com",
        source_icon: "https://n.bytvi.com/banglatribune.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "entertainment"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: "",
        comments: [
            {
                id: 1,
                user: 'Sifat',
                comment: 'Great article!',
                timestamp: '2h ago',
                reactions: { like: 1 },
                userReaction: undefined,
                replies: [
                    {
                        id: 11,
                        user: 'Rafi',
                        comment: 'I agree!',
                        timestamp: '1h ago',
                        reactions: { like: 2 },
                        userReaction: undefined,
                        replies: []
                    }
                ]
            },
            {
                id: 2,
                user: 'Anis',
                comment: 'Very informative.',
                timestamp: '1h ago',
                reactions: { like: 10 },
                userReaction: undefined,
                replies: []
            }
        ]
    },
    {
        article_id: "8872384fb0532d2ea8ae992db486269c",
        title: "মানিকগঞ্জে ২৪ ঘণ্টায় হাসপাতালে ভর্তি ৩২ ডেঙ্গু রোগী",
        link: "https://www.risingbd.com/bangladesh/news/619436",
        keywords: ["ডেঙ্গু", "ঘণ্টায়", "risingbd online", "সারা বাংলা", "রাইজিংবিডি", "online news", "news", "রোগী", "risingbd", "online news portal", "মানিকগঞ্জে", "ভর্তি", "হাসপাতালে", "২৪", "৩২", "risingbd.com"],
        creator: ["মানিকগঞ্জ প্রতিনিধি"],
        description: "মানিকগঞ্জে গত ২৪ ঘণ্টায় নতুন করে আরো ৩২ জন ডেঙ্গু রোগী ভর্তি হয়েছেন। এর মধ্যে সরকারি হাসপাতালে ভর্তি হয়েছেন তিন জন এবং বেসরকারি হাসপাতালে ভর্তি হয়েছেন ২৯ জন।",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:41:24",
        pubDateTZ: "UTC",
        image_url: "https://cdn.risingbd.com/media/imgAll/2025August/Sivilsarjon-Manikganj-2508280741.jpg",
        video_url: null,
        source_id: "risingbd",
        source_name: "Risingbd",
        source_priority: 1729180,
        source_url: "https://www.risingbd.com",
        source_icon: "https://n.bytvi.com/risingbd.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "lifestyle"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: "",
        comments: [
            {
                id: 1,
                user: 'Mina',
                comment: 'Hope everyone recovers soon!',
                timestamp: '3h ago',
                reactions: { like: 3, love: 1 },
                userReaction: undefined,
                replies: [
                    {
                        id: 11,
                        user: 'Rafi',
                        comment: 'Hospitals are working hard.',
                        timestamp: '2h ago',
                        reactions: { like: 1 },
                        userReaction: undefined,
                        replies: []
                    }
                ]
            },
            {
                id: 2,
                user: 'Tania',
                comment: 'Dengue is scary!',
                timestamp: '1h ago',
                reactions: { haha: 2 },
                userReaction: undefined,
                replies: []
            }
        ]
    },
    {
        article_id: "0ce48ac3b503134647d4af7596cd618d",
        title: "লতিফ সিদ্দিকীসহ ঢাবির শিক্ষককে অবরুদ্ধ, পুলিশে সোপর্দ",
        link: "https://www.prothomalo.com/bangladesh/capital/ltiph-siddikiish-ddhaabir-shiksskke-abruddh-pulishe-soprd",
        keywords: ["জুলাই যোদ্ধা", "ডিআরইউ", "শেখ হাফিজুর রহমান", "আবদুল লতিফ সিদ্দিকী", "পুলিশ", "রাজধানী", "অবরুদ্ধ"],
        creator: ["শর্টস"],
        description: "লতিফ সিদ্দিকীসহ ঢাবির শিক্ষককে অবরুদ্ধ, পুলিশে সোপর্দ",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:41:20",
        pubDateTZ: "UTC",
        image_url: "https://media.prothomalo.com/prothomalo-bangla%2F2025-08-28%2Fvhq0sqln%2F01.jpg?ar=40%3A21&auto=format%2Ccompress&mode=crop&ogImage=true&overlay=https%3A%2F%2Fmedia.prothomalo.com%2Fprothomalo-bangla%2F2024-08-31%2F1m4oa2xi%2FBanner_7814X143.jpg&overlay_position=bottom&overlay_width_pct=1&rect=0%2C31%2C1080%2C567&w=1200",
        video_url: null,
        source_id: "prothomalo",
        source_name: "প্রথম আলো | বাংলা নিউজ পেপার",
        source_priority: 22124,
        source_url: "https://www.prothomalo.com",
        source_icon: "https://n.bytvi.com/prothomalo.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "lifestyle"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: "",
        comments: [
            {
                id: 1,
                user: 'Rafi',
                comment: 'Unbelievable news!',
                timestamp: '4h ago',
                reactions: { like: 2 },
                userReaction: undefined,
                replies: [
                    {
                        id: 11,
                        user: 'Mina',
                        comment: 'Police did the right thing.',
                        timestamp: '3h ago',
                        reactions: { love: 1 },
                        userReaction: undefined,
                        replies: []
                    }
                ]
            }
        ]
    },
    {
        article_id: "3b8e7491f368f551fa254f39aa6f6d51",
        title: "অল্প কয়েকটি উপকরণে তৈরি 'মাছের ডিমের কালিয়া'",
        link: "https://www.risingbd.com/lifestyle/cooking%20/619435",
        keywords: ["জীবনযাপন"],
        creator: ["লাইফস্টাইল ডেস্ক"],
        description: "ভাত বা পোলাওর সঙ্গে পরিবেশন করা যায় মাছের ডিমের কালিয়া।",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:41:06",
        pubDateTZ: "UTC",
        image_url: "https://cdn.risingbd.com/media/imgAll/2025August/EGG-KALIA-2508280741.jpg",
        video_url: null,
        source_id: "risingbd",
        source_name: "Risingbd",
        source_priority: 1729180,
        source_url: "https://www.risingbd.com",
        source_icon: "https://n.bytvi.com/risingbd.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "lifestyle"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: "",
        comments: [
            {
                id: 1,
                user: 'Tania',
                comment: 'I want to try this recipe!',
                timestamp: '2h ago',
                reactions: { like: 1 },
                userReaction: undefined,
                replies: []
            }
        ]
    },
    {
        article_id: "4bcec6b363ed1b36274180aa2409b5bd",
        title: "গয়েশ্বর চন্দ্র রায়ের দুর্নীতি মামলার রায় পেছাল",
        link: "https://www.ittefaq.com.bd/749168/%E0%A6%97%E0%A6%AF%E0%A6%BC%E0%A7%87%E0%A6%B6%E0%A7%8D%E0%A6%AC%E0%A6%B0-%E0%A6%9A%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A7%8D%E0%A6%B0-%E0%A6%B0%E0%A6%BE%E0%A6%AF%E0%A6%BC%E0%A7%87%E0%A6%B0-%E0%A6%A6%E0%A7%81%E0%A6%B0%E0%A7%8D%E0%A6%A8%E0%A7%80%E0%A6%A4%E0%A6%BF-%E0%A6%AE%E0%A6%BE%E0%A6%AE%E0%A6%B2%E0%A6%BE%E0%A6%B0-%E0%A6%B0%E0%A6%BE%E0%A6%AF%E0%A6%BC-%E0%A6%AA%E0%A7%87%E0%A6%9B%E0%A6%BE%E0%A6%B2",
        keywords: ["দুদক", "আইন আদালত", "মামলা"],
        creator: ["ইত্তেফাক ডিজিটাল রিপোর্ট"],
        description: "বিএনপির স্থায়ী কমিটির সদস্য গয়েশ্বর চন্দ্র রায়ের অবৈধ সম্পদ অর্জনের মামলার রায় পিছিয়েছে। রায় শুনতে বৃহস্পতিবার আদালতে হাজির হয়েছিলেন গয়েশ্বর চন্দ্র রায়। রায়ের দিন বদলের খবর শুনে পরে তিনি চলে যান।বৃহস্পতিবার (২৮ আগস্ট) ঢাকার তৃতীয় বিশেষ জজ আদালতে এ রায় ঘোষণার তারিখ ছিল। কিন্তু রায় প্রস্তুত না হওয়ায় বিচারক মুহা. আবু তাহের রায়ের নতুন তারিখ ৪ সেপ্টেম্বর ঠিক করে দেন বলে জানিয়েছেন দুদকের কৌঁসুলি...বিস্তারিত",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:40:34",
        pubDateTZ: "UTC",
        image_url: "https://cdn.ittefaqbd.com/contents/cache/images/800x450x1/uploads/media/2025/08/28/78244fb5c7eb9d26d6a4e52c96c5abb7-68b007b681a3b.jpg?jadewits_media_id=245448",
        video_url: null,
        source_id: "ittefaq",
        source_name: "দৈনিক ইত্তেফাক | The Daily Ittefaq",
        source_priority: 118342,
        source_url: "http://ittefaq.com.bd",
        source_icon: "https://n.bytvi.com/ittefaq.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "lifestyle"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: "",
        comments: [
            {
                id: 1,
                user: 'Sifat',
                comment: 'Justice delayed again...',
                timestamp: '5h ago',
                reactions: { like: 2 },
                userReaction: undefined,
                replies: [
                    {
                        id: 11,
                        user: 'Anis',
                        comment: 'Hope for a fair verdict soon.',
                        timestamp: '4h ago',
                        reactions: { like: 1 },
                        userReaction: undefined,
                        replies: []
                    }
                ]
            }
        ]
    },
    {
        article_id: "af830d3e30a6338ba0ad3d746329269f",
        title: "গয়েশ্বরের দুর্নীতি মামলার রায় পেছালো",
        link: "https://www.banglatribune.com/others/912948/%E0%A6%97%E0%A7%9F%E0%A7%87%E0%A6%B6%E0%A7%8D%E0%A6%AC%E0%A6%B0%E0%A7%87%E0%A6%B0-%E0%A6%A6%E0%A7%81%E0%A6%B0%E0%A7%8D%E0%A6%A8%E0%A7%80%E0%A6%A4%E0%A6%BF-%E0%A6%AE%E0%A6%BE%E0%A6%AE%E0%A6%B2%E0%A6%BE%E0%A6%B0-%E0%A6%B0%E0%A6%BE%E0%A7%9F-%E0%A6%AA%E0%A7%87%E0%A6%9B%E0%A6%BE%E0%A6%B2%E0%A7%8D%E0%A6%93",
        keywords: ["গয়েশ্বর", "আদালত"],
        creator: ["বাংলা ট্রিবিউন রিপোর্ট"],
        description: "বিএনপির স্থায়ী কমিটির সদস্য ও সাবেক মন্ত্রী গয়েশ্বর চন্দ্র রায়ের বিরুদ্ধে দুর্নীতি দমন কমিশনের (দুদক) মমলার রায় পিছিয়েছে। রয়ের জন্য আগামী ৪ সেপ্টেম্বর দিন ধার্য করেছেন আদালত।বৃহস্পতিবার (২৮ আগস্ট) ঢাকার বিশেষ জজ আদালত-৩ এর বিচারক মুহা. আবু তাহেরের আদালত এ আদেশ দেন।আদালত সূত্রে জানা গেছে, আজ রায় প্রস্তুত না হওয়ায় নতুন দিন ধার্য করেন বিচারক। এর আগে, মামলার যুক্তিতর্ক শেষে রায়ের জন্য ২৮ আগস্ট...বিস্তারিত",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:38:31",
        pubDateTZ: "UTC",
        image_url: "https://cdn.banglatribune.net/contents/cache/images/800x450x1/uploads/media/2025/08/28/Untitled-1-e8bb17d27308d39c55a564b19e3976e7.jpg?jadewits_media_id=990908",
        video_url: null,
        source_id: "banglatribune",
        source_name: "Bangla Tribuna",
        source_priority: 685343,
        source_url: "https://www.banglatribune.com",
        source_icon: "https://n.bytvi.com/banglatribune.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "lifestyle"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "3ac6f1ca4c9e64c76b2296911501ab6a",
        title: "দাদি ও ফুফুকে হত্যার পর 'চোর-পুলিশ' খেলছিল সাইফুল",
        link: "https://www.ittefaq.com.bd/749167/%E0%A6%A6%E0%A6%BE%E0%A6%A6%E0%A6%BF-%E0%A6%93-%E0%A6%AB%E0%A7%81%E0%A6%AB%E0%A7%81%E0%A6%95%E0%A7%87-%E0%A6%B9%E0%A6%A4%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%B0-%E0%A6%AA%E0%A6%B0-%E2%80%98%E0%A6%9A%E0%A7%8B%E0%A6%B0-%E0%A6%AA%E0%A7%81%E0%A6%B2%E0%A6%BF%E0%A6%B6%E2%80%99-%E0%A6%96%E0%A7%87%E0%A6%B2%E0%A6%9B%E0%A6%BF%E0%A6%B2-%E0%A6%B8%E0%A6%BE%E0%A6%87%E0%A6%AB%E0%A7%81%E0%A6%B2",
        keywords: ["হত্যা", "পুলিশ", "খাগড়াছড়ি"],
        creator: ["খাগড়াছড়ি প্রতিনিধি"],
        description: "খাগড়াছড়ির রামগড়ে ঘরের ভেতর থেকে মা-মেয়ের গলাকাটা মরদেহ উদ্ধারের ৬ দিন পর হত্যাকাণ্ডে জড়িত সাইफুলকে গ্রেপ্তার করেছে পুলিশ। জমিজমার সংক্রান্ত বিরোধের জেরেই এ জোড়া খুনের ঘটনা ঘটেছে বলে ভাষ্য পুলিশের।পুলিশ বলছে, সাইफুলকে আরও আগে শনাক্ত করা গেলেও গ্রেপ্তার এড়াতে বার বার স্থান পরিবর্তন করছিলেন তিনি। তাই তাকে গ্রেপ্তারে বেগ পেতে হয়েছে।বৃহস্পতিবার (২৮ আগস্ট) খাগড়াছড়ি পুলিশ সুপার মো. আরেফিন জুয়েল...বিস্তারিত",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:37:49",
        pubDateTZ: "UTC",
        image_url: "https://cdn.ittefaqbd.com/contents/cache/images/800x450x1/uploads/media/2025/08/28/25eee4cefbd42e1bd5ff251746d7afda-68b00684613f1.jpg?jadewits_media_id=245446",
        video_url: null,
        source_id: "ittefaq",
        source_name: "দৈনিক ইত্তেফাক | The Daily Ittefaq",
        source_priority: 118342,
        source_url: "http://ittefaq.com.bd",
        source_icon: "https://n.bytvi.com/ittefaq.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "lifestyle"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "3eec73f1068dba5a21e0118e0264a744",
        title: "তৃতীয় রাউন্ডে আলকারেজ, শুরুর ধাক্কা সামলেছেন জোকোভিচও",
        link: "https://www.banglatribune.com/sport/tennis/912947/%E0%A6%A4%E0%A7%83%E0%A6%A4%E0%A7%80%E0%A7%9F-%E0%A6%B0%E0%A6%BE%E0%A6%89%E0%A6%A8%E0%A7%8D%E0%A6%A1%E0%A7%87-%E0%A6%86%E0%A6%B2%E0%A6%95%E0%A6%BE%E0%A6%B0%E0%A7%87%E0%A6%9C-%E0%A6%B6%E0%A7%81%E0%A6%B0%E0%A7%81%E0%A6%B0-%E0%A6%A7%E0%A6%BE%E0%A6%95%E0%A7%8D%E0%A6%95%E0%A6%BE-%E0%A6%B8%E0%A6%BE%E0%A6%AE%E0%A6%B2%E0%A7%87%E0%A6%9B%E0%A7%87%E0%A6%A8",
        keywords: ["ইউএস ওপেন", "কার্লোস আলকারেজ", "নোভাক জোকোভিচ"],
        creator: ["স্পোর্টস ডেস্ক"],
        description: "ইউএস ওপেনে সহজ জয়ে তৃতীয় রাউন্ড নিশ্চিত করেছেন ফেভারিট কার্লোস আলকারেজ। আরেক ফেভারিট নোভাক জোকোভিচ অবশ্য শুরুতেই ধাক্কা খেয়েছিলেন। পরে সেই ধাক্কা কাটিয়ে নিশ্চিত করেছেন তৃতীয় রাউন্ড। দ্বিতীয় রাউন্ডে ইতালির মাত্তিয়া বেলুচ্চিকে সরাসরি সেটে ৬-১, ৬-০, ৬-۳ গেমে উড়িয়ে দিয়েছেন আলকারেজ। তাও আবার সেটা করেছেন এক ঘণ্টা ৩৬ মিনিটের লড়াইয়ে। বেলুচ্চির বিপক্ষে একেবারে অপ্রতিরোধ্য ছিলেন ২২ বছর বয়সী...বিস্তারিত",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:37:07",
        pubDateTZ: "UTC",
        image_url: "https://cdn.banglatribune.net/contents/cache/images/800x450x1/uploads/media/2025/08/28/-36ed9714d6a7f2b7a9e7e5c1f1de403b.JPG?jadewits_media_id=990907",
        video_url: null,
        source_id: "banglatribune",
        source_name: "Bangla Tribuna",
        source_priority: 685343,
        source_url: "https://www.banglatribune.com",
        source_icon: "https://n.bytvi.com/banglatribune.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "lifestyle"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "d81060a7035a103ba826a17f808db2dc",
        title: "লোহাগড়ায় অপারেশন থিয়েটারে অচেতন রোগীর সঙ্গে নার্সের টিকটক",
        link: "https://www.ittefaq.com.bd/749166/%E0%A6%B2%E0%A7%8B%E0%A6%B9%E0%A6%BE%E0%A6%97%E0%A7%9C%E0%A6%BE%E0%A7%9F-%E0%A6%85%E0%A6%AA%E0%A6%BE%E0%A6%B0%E0%A7%87%E0%A6%B6%E0%A6%A8-%E0%A6%A5%E0%A6%BF%E0%A7%9F%E0%A7%87%E0%A6%9F%E0%A6%BE%E0%A6%B0%E0%A7%87-%E0%A6%85%E0%A6%9A%E0%A7%87%E0%A6%A4%E0%A6%A8-%E0%A6%B0%E0%A7%8B%E0%A6%97%E0%A7%80%E0%A6%B0-%E0%A6%B8%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A7%87",
        keywords: ["নড়াইল", "সারাদেশ"],
        creator: ["লোহাগড়া (নড়াইল) সংবাদদাতা"],
        description: "নড়াইলের লোহাগড়া পৌর শহরের জয়পুর মোড়ে অবস্থিত 'প্রত্যাশা ক্লিনিক'-এ অপারেশন থিয়েটারে অচেতন এক প্রসূতির পাশে দাঁড়িয়ে নার্স প্রিয়া টিকটক ভিডিও ধারণ করে তা সামাজিক মাধ্যমে ছড়িয়ে দিয়েছেন। বুধবার (২৭ আগস্ট) রাতে ভিডিওটি ফেসবুকে ছড়িয়ে পড়লে ব্যাপক সমালোচনার সৃষ্টি হয়। ঘটনাটি স্থানীয়দের মধ্যে তীব্র ক্ষোভ ও উদ্বেগের জন্ম দিয়েছে।ভিডিওটিতে দেখা যায়, অপারেশন থিয়েটারের পরিবেশে রোগীর...বিস্তারিত",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:36:34",
        pubDateTZ: "UTC",
        image_url: "https://cdn.ittefaqbd.com/contents/cache/images/800x450x1/uploads/media/2025/08/28/a11f02043db04dacb53087af7585eda2-68b006d3a7436.jpg?jadewits_media_id=245447",
        video_url: null,
        source_id: "ittefaq",
        source_name: "দৈনিক ইত্তেফাক | The Daily Ittefaq",
        source_priority: 118342,
        source_url: "http://ittefaq.com.bd",
        source_icon: "https://n.bytvi.com/ittefaq.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "lifestyle"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "d2af4c0f9099f9bd00a906258b9d061b",
        title: "ঘণ্টাব্যাপী অবরোধের পর আগারগাঁও মোড় ছাড়লেন শিক্ষার্থীরা, যান চলাচল শুরু",
        link: "https://www.prothomalo.com/bangladesh/capital/2bz86kyerj",
        keywords: ["শিক্ষার্থী", "ঢাকা", "অবরোধ"],
        creator: ["নিজস্ব প্রতিবেদক"],
        description: "দাবি আদায়ে ভবিষ্যতে ধারাবাহিক আন্দোলনের হুঁশিয়ারি দিয়ে দুপুর সাড়ে ১২টার পর সড়ক ছেড়ে দেন শিক্ষার্থীরা। এরপর যান চলাচল শুরু হয়।",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:35:34",
        pubDateTZ: "UTC",
        image_url: "https://media.prothomalo.com/prothomalo-bangla%2F2025-08-28%2F5gv2g7n6%2FBlocked.jpeg?ar=40%3A21&auto=format%2Ccompress&mode=crop&ogImage=true&overlay=https%3A%2F%2Fmedia.prothomalo.com%2Fprothomalo-bangla%2F2024-08-31%2F1m4oa2xi%2FBanner_7814X143.jpg&overlay_position=bottom&overlay_width_pct=1&rect=0%2C0%2C1280%2C672&w=1200",
        video_url: null,
        source_id: "prothomalo",
        source_name: "প্রথম আলো | বাংলা নিউজ পেপার",
        source_priority: 22124,
        source_url: "https://www.prothomalo.com",
        source_icon: "https://n.bytvi.com/prothomalo.png",
        language: "bengali",
        country: ["bangladesh"],
        category: ["top", "entertainment", "sports"],
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        ai_content: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "6b954c6f988a3473bdef809ea2830579",
        title: "Travis Kelce Jersey Sales Explode After Taylor Swift Engagement",
        link: "https://www.tmz.com/2025/08/28/travis-kelce-jersey-sales-surge-after-taylor-engagement/",
        keywords: ["শিক্ষার্থী", "ঢাকা", "অবরোধ"],
        creator: ["TMZ Staff"],
        description: "Looks like love -- and Taylor Swift -- is great for merch sales ... 'cause TMZ Sports is told Travis Kelce's jerseys flew off the shelves on Tuesday after he proposed to the pop star! Fanatics -- the official e-commerce partner of both the NFL and... Permalink",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:30:22",
        pubDateTZ: "UTC",
        image_url: "https://imagez.tmz.com/image/e7/4by3/2025/08/27/e70813fcbfef4d09a8ecca2b5ee41ba4_md.jpg",
        video_url: "",
        source_id: "tmz",
        source_name: "Tmz",
        source_priority: 2659,
        source_url: "http://www.tmz.com",
        source_icon: "https://n.bytvi.com/tmz.png",
        language: "english",
        country: ["united states of america"],
        category: ["sports"],
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "4ba4a358ce5a99e40863094fcec34e6d",
        title: "I'm a nutritionist: This is 'one of the best superfoods' you need to eat more of",
        link: "https://www.denbighshirefreepress.co.uk/news/25422213.spinach-benefits-nutritionist-shares-superfood-tips/",
        keywords: [
            "article_types:news",
            "content-level:1",
            "source:newsquest",
            "is-clone",
            "topics:health"
        ],
        creator: ["Emilia Kettle"],
        description: "Spinach is up there as one of the most popular superfoods as it's rich in Iron, Vitamin C and E, potassium and magnesium.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:28:02",
        pubDateTZ: "UTC",
        image_url: "https://www.denbighshirefreepress.co.uk/resources/images/19887046.jpg?type=mds-article-575",
        video_url: "",
        source_id: "denbighshirefreepress",
        source_name: "Denbighshirefreepress Co Uk",
        source_priority: 374771,
        source_url: "https://www.denbighshirefreepress.co.uk",
        source_icon: "https://n.bytvi.com/denbighshirefreepress.png",
        language: "english",
        country: ["united kingdom"],
        category: ["top", "health"],
        duplicate: true,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "5ef7cde2e5b602a3a7a3d22394f7cb88",
        title: "I'm a nutritionist: This is 'one of the best superfoods' you need to eat more of",
        link: "https://www.rhyljournal.co.uk/news/25422213.spinach-benefits-nutritionist-shares-superfood-tips/",
        keywords: [
            "is-clone",
            "content-level:1",
            "topics:health",
            "article_types:news",
            "source:newsquest"
        ],
        creator: ["Emilia Kettle"],
        description: "Spinach is up there as one of the most popular superfoods as it's rich in Iron, Vitamin C and E, potassium and magnesium.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:28:02",
        pubDateTZ: "UTC",
        image_url: "https://www.rhyljournal.co.uk/resources/images/19887046/?htype=0&type=app",
        video_url: "",
        source_id: "rhyljournal",
        source_name: "Rhyljournal Co Uk",
        source_priority: 2358290,
        source_url: "https://www.rhyljournal.co.uk",
        source_icon: "https://n.bytvi.com/rhyljournal.png",
        language: "english",
        country: ["united kingdom"],
        category: ["top", "health"],
        duplicate: true,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "e6d71aada987fd0440c78eefc6cdb940",
        title: "I'm a nutritionist: This is 'one of the best superfoods' you need to eat more of",
        link: "https://www.northwalespioneer.co.uk/news/25422213.spinach-benefits-nutritionist-shares-superfood-tips/",
        keywords: [
            "content-level:1",
            "topics:health",
            "is-clone",
            "article_types:news",
            "source:newsquest"
        ],
        creator: ["Emilia Kettle"],
        description: "Spinach is up there as one of the most popular superfoods as it's rich in Iron, Vitamin C and E, potassium and magnesium.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:28:02",
        pubDateTZ: "UTC",
        image_url: "https://www.northwalespioneer.co.uk/resources/images/19887046/?htype=0&type=app",
        video_url: "",
        source_id: "northwalespioneer",
        source_name: "Northwalespioneer Co Uk",
        source_priority: 1008924,
        source_url: "https://www.northwalespioneer.co.uk",
        source_icon: "https://n.bytvi.com/northwalespioneer.png",
        language: "english",
        country: ["united kingdom"],
        category: ["top", "health"],
        duplicate: true,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "82db1767c7ba35972f608a8f64e75af1",
        title: "Top BBC chef to close Michelin-starred restaurant after 8 years in business & says he’s ‘unable to reach a resolution’",
        link: "https://www.thesun.co.uk/money/36458678/bbc-chef-closes-michelin-star-restaurant/",
        keywords: ["bbc", "money", "masterchef", "trends", "news money", "store closings"],
        creator: ["Milly Morgan"],
        description: "A TOP BBC chef has announced the closure of his two Michelin-starred restaurant after eight years in business, as he confessed he is \"unable to reach",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:27:40",
        pubDateTZ: "UTC",
        image_url: "https://www.thesun.co.uk/wp-content/uploads/2025/08/2f44wrc-claude-bosi-bibendum-michelin-1018774313_2af0ea.jpg?w=620",
        video_url: "",
        source_id: "thesun",
        source_name: "The Sun",
        source_priority: 1813,
        source_url: "https://www.thesun.co.uk",
        source_icon: "https://n.bytvi.com/thesun.png",
        language: "english",
        country: ["united kingdom"],
        category: ["business"],
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "5e8615c450825f1d8c15da90ade6ab25",
        title: "Top BBC chef to close Michelin-starred restaurant after 8 years in business & says he’s ‘unable to reach a resolution’",
        link: "https://www.thescottishsun.co.uk/money/15267109/bbc-chef-closes-michelin-star-restaurant/",
        keywords: ["bbc", "masterchef 2018", "money", "store closings", "news money", "trends"],
        creator: ["Milly Morgan"],
        description: "A TOP BBC chef has announced the closure of his two Michelin-starred restaurant after eight years in business, as he confessed he is \"unable to reach",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:27:40",
        pubDateTZ: "UTC",
        image_url: "https://www.thescottishsun.co.uk/wp-content/uploads/sites/2/2025/08/2f44wrc-claude-bosi-bibendum-michelin-1018774313_2af0ea.jpg?w=620",
        video_url: "",
        source_id: "thescottishsun",
        source_name: "The Scottish Sun",
        source_priority: 31532,
        source_url: "https://www.thescottishsun.co.uk",
        source_icon: "https://n.bytvi.com/thescottishsun.png",
        language: "english",
        country: ["united kingdom"],
        category: ["business"],
        duplicate: true,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "491da5b269ebabfa296679d4b40fd91e",
        title: "Asda opening 20 new stores this year with full list of locations announced",
        link: "https://www.mirror.co.uk/money/asda-opening-20-new-stores-35805423",
        keywords: ["money"],
        creator: ["mirrornews@mirror.co.uk (Levi Winchester)"],
        description: "The first new Asda Express will open in Castleford in early October, followed by openings in more locations from later that month - see the full list of places below",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:25:52",
        pubDateTZ: "UTC",
        image_url: "https://i2-prod.mirror.co.uk/incoming/article35470849.ece/ALTERNATES/s615/0_Green-Initiatives-Inside-Asdas-New-Sustainability-Store.jpg",
        video_url: "",
        source_id: "mirroruk",
        source_name: "Mirror",
        source_priority: 910,
        source_url: "https://www.mirror.co.uk",
        source_icon: "https://n.bytvi.com/mirroruk.png",
        language: "english",
        country: ["united kingdom"],
        category: ["top", "business"],
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "0962e5003865a33362f8c43352437806",
        title: "Deux heures de parking à Bruxelles au prix d’une pizza !",
        link: "https://www.dhnet.be/actu/edito/2025/08/28/deux-heures-de-parking-a-bruxelles-au-prix-dune-pizza-MYYPKTMTRVGUHLF4YDOAMRDCAQ/",
        keywords: ["edito"],
        creator: ["Vincent Schmidt"],
        description: "La Dernière Humeur est signée Vincent Schmidt. ...",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:17:23",
        pubDateTZ: "UTC",
        image_url: "https://www.dhnet.be/resizer/v2/N5RKLGP5DJESLHSJIMRXJPF74Q.jpg?auth=ee945b16871d3842a5263abcf21868f72035970bd0a8e259e5e085713b9cd11a&focal=3096%2C2064&height=800&quality=85&width=1200",
        video_url: "",
        source_id: "dhnet",
        source_name: "Dh",
        source_priority: 337210,
        source_url: "https://www.dhnet.be",
        source_icon: "https://n.bytvi.com/dhnet.png",
        language: "french",
        country: ["belgium"],
        category: ["top", "lifestyle"],
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "869ed8b90d930e7ad78908cf3492c376",
        title: "A guide to East City’s hottest block, Harrington Street",
        link: "https://www.capetownmagazine.com/nightlife-cape-town/a-guide-to-east-citys-hottest-block-harrington-street/26_22_22029",
        keywords: [
            "east city bars",
            "live music cape town",
            "venue hire cape town",
            "first thursdays events",
            "nightclubs cape town",
            "cocktails cape town",
            "harrington street"
        ],
        creator: ["Cape Town's no.1 Online Magazine: Exciting Events and Things To Do"],
        description: "From dazzling disco & whiskey dinners to live music",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:14:20",
        pubDateTZ: "UTC",
        image_url: "https://www.capetownmagazine.com/media_lib/preview/bf76bafa66bd5eeccc6bbc0d2f468a35.preview.jpg",
        video_url: "",
        source_id: "capetown",
        source_name: "Cape Town's",
        source_priority: 642764,
        source_url: "https://www.capetownmagazine.com",
        source_icon: "https://n.bytvi.com/capetown.png",
        language: "english",
        country: ["south africa"],
        category: ["tourism"],
        duplicate: false,
        author: "",
        date: "",
        snippet: ""
    },
    {
        article_id: "7402ee68ccc5aeff41b257c528538653",
        title: "Đóng hay mở nắp hộp thức ăn khi quay trong lò vi sóng? Thì ra bấy lâu rất nhiều người hiểu sai",
        link: "https://cafebiz.vn/dong-hay-mo-nap-hop-thuc-an-khi-quay-trong-lo-vi-song-thi-ra-bay-lau-rat-nhieu-nguoi-hieu-sai-176250828134354312.chn",
        keywords: ["lò vi sóng", "sức khỏe", "món ăn", "đóng nắp hộp thức ăn", "mở nắp hộp thức ăn"],
        creator: ["Theo Phác Thái Anh"],
        description: "Việc đóng hay mở nắp hộp thức ăn khi quay trong lò vi sóng ảnh hưởng lớn đến chất lượng món ăn và sức khỏe của người sử dụng.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        pubDate: "2025-08-28 07:11:00",
        pubDateTZ: "UTC",
        image_url: "https://cafebiz.cafebizcdn.vn/zoom/700_438/162123310254002176/2025/8/28/avatar1756363401615-1756363401994809684428.png",
        video_url: "",
        source_id: "cafebiz",
        source_name: "Cafebiz",
        source_priority: 619255,
        source_url: "https://cafebiz.vn",
        source_icon: "https://n.bytvi.com/cafebiz.png",
        language: "vietnamese",
        country: ["vietnam"],
        category: ["business"],
        duplicate: true,
        author: "",
        date: "",
        snippet: ""
    }
];
